version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/local/php/Dockerfile
      args:
        - "UID=${UID:-1000}"
    working_dir: /var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
    volumes:
      - ./source:/var/www/html/
      - ./docker/php/logs:/var/log
      - ./docker/apache-mods/deflate.conf:/etc/apache2/mods-available/deflate.conf
      - ./docker/local/php/curl.ini:/usr/local/etc/php/conf.d/curl.ini
      - ./docker/local/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - traefik.frontend.rule=Host:symfony-immo.dev.localhost
      - traefik.docker.network=backend

  node:
      build:
        context: .
        dockerfile: ./docker/local/node/Dockerfile
        args:
          - "UID=${UID:-1000}"
      working_dir: /srv/app/
      tty: true
      user: node
      networks:
        - backend
      volumes:
        - ./source:/srv/app
      labels:
        - traefik.port=8080

networks:
  backend:
    external: true